// Generates src/renderer/src/assets/<sprite>/manifest.ts from the sprite
// strips in that directory. Every sheet is a horizontal strip of uniform
// frames, so the frame count is width / frameSize read straight from the
// PNG header. Per-state playback metadata (fps, loop, impactFrame) is
// authored here — impactFrame is the synchronization contract between an
// animation and the OS action it decorates.
//
// Usage: node scripts/pack-sprites.js [sprite ...]   (default: all)
// Adding a sprite: drop strips in assets/<id>/, add a SPRITES entry here,
// then write its definition in renderer/src/sprites/<id>/.

const { readFileSync, writeFileSync, readdirSync } = require("node:fs");
const { join, basename } = require("node:path");

const ASSETS_DIR = join(__dirname, "..", "src", "renderer", "src", "assets");

const SPRITES = {
  jeb: {
    frameSize: 96,
    scale: 2,
    // Non-state assets living in the same directory (props, projectiles).
    extras: ["shuriken"],
    states: {
      idle: { fps: 8, loop: true },
      walk: { fps: 10, loop: true },
      run: { fps: 14, loop: true },
      dash: { fps: 16, loop: true },
      "jump-start": { fps: 14, loop: false },
      jump: { fps: 10, loop: true },
      "jump-transition": { fps: 14, loop: false },
      "jump-fall": { fps: 10, loop: true },
      "wall-contact": { fps: 12, loop: false },
      "wall-slide": { fps: 10, loop: true },
      "wall-jump": { fps: 14, loop: false },
      climbing: { fps: 10, loop: true },
      "attack-1": { fps: 14, loop: false, impactFrame: 3 },
      "attack-2": { fps: 14, loop: false, impactFrame: 4 },
      "attack-3": { fps: 14, loop: false, impactFrame: 3 },
      "air-attack": { fps: 14, loop: false, impactFrame: 3 },
      "special-attack": { fps: 14, loop: false, impactFrame: 9 },
      throw: { fps: 14, loop: false, impactFrame: 5 },
      defend: { fps: 10, loop: false, holdLast: true },
      hurt: { fps: 10, loop: false },
      death: { fps: 10, loop: false, holdLast: true },
      healing: { fps: 10, loop: true },
      "healing-no-effect": { fps: 10, loop: true },
      // typing.png hosts two states: the sit-down transition and the loop.
      "typing-start": {
        fps: 12,
        loop: false,
        sheet: "typing.png",
        start: 0,
        frames: 8,
      },
      typing: { fps: 8, loop: true, sheet: "typing.png", start: 8, frames: 8 },
    },
  },
};

function pngWidth(path) {
  const buf = readFileSync(path);
  if (buf.readUInt32BE(12) !== 0x49484452) {
    throw new Error(`${path}: IHDR not where expected`);
  }
  return buf.readUInt32BE(16);
}

function pack(id, config) {
  const dir = join(ASSETS_DIR, id);
  const extras = new Set(config.extras ?? []);
  const manifest = {
    frameSize: config.frameSize,
    scale: config.scale,
    states: {},
  };

  // States that name their sheet explicitly (with start/frames) share a
  // strip; their sheets are excluded from the one-strip-per-state pass.
  const sharedSheets = new Set();
  for (const [name, meta] of Object.entries(config.states)) {
    if (!meta.sheet) continue;
    sharedSheets.add(meta.sheet);
    const width = pngWidth(join(dir, meta.sheet));
    const available = Math.floor(width / config.frameSize);
    if ((meta.start ?? 0) + meta.frames > available) {
      throw new Error(
        `${id}/${meta.sheet}: state ${name} wants frames ${meta.start ?? 0}..${
          (meta.start ?? 0) + meta.frames
        } but the strip has ${available}`,
      );
    }
    manifest.states[name] = { ...meta };
  }

  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith(".png")) continue;
    const name = basename(file, ".png");
    if (extras.has(name) || sharedSheets.has(file)) continue;
    const meta = config.states[name];
    if (!meta) throw new Error(`${id}: no state metadata for sheet ${file}`);
    const width = pngWidth(join(dir, file));
    if (width % config.frameSize !== 0) {
      throw new Error(
        `${id}/${file}: width ${width} not a multiple of ${config.frameSize}`,
      );
    }
    manifest.states[name] = {
      sheet: file,
      frames: width / config.frameSize,
      ...meta,
    };
  }

  for (const name of Object.keys(config.states)) {
    if (!manifest.states[name]) {
      throw new Error(`${id}: missing sheet for state ${name}`);
    }
  }

  const constName = `${id.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_MANIFEST`;
  const ts = `// Generated by scripts/pack-sprites.js — do not edit by hand.
import type { SpriteManifest } from "../../sprites/types";

export const ${constName}: SpriteManifest = ${JSON.stringify(manifest, null, 2)};
`;
  writeFileSync(join(dir, "manifest.ts"), ts);
  console.log(
    `${id}: wrote manifest for ${Object.keys(manifest.states).length} states.`,
  );
}

const requested = process.argv.slice(2);
const ids = requested.length > 0 ? requested : Object.keys(SPRITES);
for (const id of ids) {
  const config = SPRITES[id];
  if (!config) throw new Error(`Unknown sprite "${id}"`);
  pack(id, config);
}
